server:
  port: 10009

###### swagger配置开始 ######
group: 用户服务 # 定义全局变量
knife4j:
  # 开启 Swagger 模块和API排序等其他配置功能
  enable: true
  # 开启生产环境屏蔽
  production: false
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    # enable: true
    # Basic认证用户名
    #username: test
    # Basic认证密码
    #password: 123
  setting:
    # 禁用调试功能 true不禁用，false禁用
    enable-debug: true
    enable-swagger-models: true
    swagger-model-name: 我是自定义的Model名称
  documents:
    - group: ${group}
      name: 补充说明文档
      # 某一个文件夹下所有的.md文件
      locations: classpath:markdown/*

#    - group: ${group}
#      name: 接口签名
#      # 某一个文件夹下单个.md文件
#      locations: classpath:markdown/sign.md
###### swagger配置结束 ######